[build-system]
requires = ["setuptools==60.9.3", "setuptools-scm==7.0.5", "wheel==0.37.1", "auditwheel==5.1.2"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-Wall -rsx -vv -s"
markers = [
    "skip_browser",
    "only_browser",
    "skip_platform",
    "only_platform"
]
junit_family = "xunit2"
asyncio_mode = "auto"

[tool.mypy]
ignore_missing_imports = true
python_version = "3.7"
warn_unused_ignores = false
warn_redundant_casts = true
warn_unused_configs = true
check_untyped_defs = true
disallow_untyped_defs = true
exclude = ["examples"]

[[tool.mypy.overrides]]
module = "tests/async.*"
ignore_errors = true

[tool.isort]
profile = "black"

[tool.pyright]
include = ["playwright", "tests/sync"]
ignore = ["tests/async/", "scripts/", "examples/"]
pythonVersion = "3.7"
reportMissingImports = false
reportTypedDictNotRequiredAccess = false
reportCallInDefaultInitializer = true
